from __future__ import annotations

"""
Stage 5: Annotation Assembly

Combines extracted frames, scene analysis, object tracking, and generated QA pairs
into a single schema-valid evaluation sample JSON.
"""

import json
import hashlib
from datetime import date
from pathlib import Path
from typing import Any, Optional

from .config import PipelineConfig


def assemble_sample(
    frames: list[dict],
    qa_pairs: list[dict],
    config: PipelineConfig,
    duration_seconds: Optional[float] = None,
) -> dict:
    """
    Assemble all pipeline outputs into a schema-valid evaluation sample.

    Args:
        frames: Enriched frame dicts (with objects, scene_description)
        qa_pairs: Generated QA pairs
        config: Pipeline configuration
        duration_seconds: Total duration of the sequence (auto-computed if None)

    Returns:
        A dict conforming to annotation_schema.json
    """
    if duration_seconds is None:
        duration_seconds = _compute_duration(frames)

    # Generate a deterministic sample ID from content
    sample_id = _generate_sample_id(frames, config)

    # Clean frame data to match schema
    clean_frames = [_clean_frame(f) for f in frames]

    sample = {
        "id": sample_id,
        "version": config.schema_version,
        "visual_sequence": {
            "source": config.source_type,
            "environment": config.environment,
            "duration_seconds": duration_seconds,
            "frames": clean_frames,
        },
        "qa_pairs": qa_pairs,
        "metadata": {
            "source_dataset": config.source_type,
            "annotator": config.annotator,
            "annotation_date": date.today().isoformat(),
            "notes": (
                f"Auto-generated by curation pipeline. "
                f"Vision: {config.vision_provider}/{config.vision_model}. "
                f"QA: {config.qa_provider}/{config.qa_model}."
            ),
        },
    }

    return sample


def _clean_frame(frame: dict) -> dict:
    """Ensure a frame dict contains only schema-valid fields."""
    clean = {
        "frame_id": frame["frame_id"],
        "timestamp": frame["timestamp"],
        "image_path": frame["image_path"],
    }

    if frame.get("objects"):
        clean["objects"] = [_clean_object(obj) for obj in frame["objects"]]

    if frame.get("scene_description"):
        clean["scene_description"] = frame["scene_description"]

    return clean


def _clean_object(obj: dict) -> dict:
    """Ensure an object dict contains only schema-valid fields."""
    clean = {
        "object_id": obj.get("object_id", "unknown"),
        "label": obj.get("label", "unknown"),
    }
    if obj.get("bounding_box"):
        box = obj["bounding_box"]
        clean["bounding_box"] = {
            "x_min": float(box.get("x_min", 0)),
            "y_min": float(box.get("y_min", 0)),
            "x_max": float(box.get("x_max", 0)),
            "y_max": float(box.get("y_max", 0)),
        }
    if obj.get("state"):
        clean["state"] = obj["state"]
    if obj.get("spatial_description"):
        clean["spatial_description"] = obj["spatial_description"]
    return clean


def _compute_duration(frames: list[dict]) -> float:
    """Estimate duration from first and last frame timestamps."""
    if len(frames) < 2:
        return 0.0
    try:
        from datetime import datetime
        first = datetime.fromisoformat(frames[0]["timestamp"])
        last = datetime.fromisoformat(frames[-1]["timestamp"])
        return (last - first).total_seconds()
    except (ValueError, KeyError):
        return 0.0


def _generate_sample_id(frames: list[dict], config: PipelineConfig) -> str:
    """Generate a deterministic sample ID from the input content."""
    hasher = hashlib.md5()
    hasher.update(config.environment.encode())
    hasher.update(config.source_type.encode())
    for f in frames[:3]:  # Hash first few frames for uniqueness
        hasher.update(f.get("frame_id", "").encode())
        hasher.update(f.get("timestamp", "").encode())
    short_hash = hasher.hexdigest()[:8]
    env = config.environment.replace(" ", "_")[:20]
    return f"{env}_{short_hash}"


def save_sample(sample: dict, config: PipelineConfig) -> Path:
    """
    Validate and save the assembled sample to disk.

    Returns the path to the saved JSON file.
    """
    # Validate before saving
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent / "evaluation"))
    from validate_schema import validate_sample

    errors = validate_sample(sample)
    if errors:
        print(f"  WARNING: Sample has {len(errors)} validation error(s):")
        for e in errors:
            print(f"    - {e}")
        print("  Saving anyway for review...")

    output_dir = config.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / f"{sample['id']}.json"
    with open(output_path, "w") as f:
        json.dump(sample, f, indent=2)

    print(f"  Saved: {output_path}")
    return output_path
